// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorErrorCode.
const (
	BadRequest    ErrorErrorCode = "bad_request"
	Forbidden     ErrorErrorCode = "forbidden"
	InvalidParams ErrorErrorCode = "invalid_params"
	NotFound      ErrorErrorCode = "not_found"
	RateLimited   ErrorErrorCode = "rate_limited"
	Unauthorized  ErrorErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case Forbidden:
		return true
	case InvalidParams:
		return true
	case NotFound:
		return true
	case RateLimited:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for StockDividendSafety.
const (
	AtRisk  StockDividendSafety = "at_risk"
	Safe    StockDividendSafety = "safe"
	Unknown StockDividendSafety = "unknown"
	Watch   StockDividendSafety = "watch"
)

// Valid indicates whether the value is a known member of the StockDividendSafety enum.
func (e StockDividendSafety) Valid() bool {
	switch e {
	case AtRisk:
		return true
	case Safe:
		return true
	case Unknown:
		return true
	case Watch:
		return true
	default:
		return false
	}
}

// Calendar defines model for Calendar.
type Calendar struct {
	Days int `json:"days"`

	// From Today, UTC.
	From openapi_types.Date `json:"from"`

	// Stocks Soonest ex-date first.
	Stocks []struct {
		ExDividendDate openapi_types.Date `json:"ex_dividend_date"`
		Name           *string            `json:"name,omitempty"`

		// PaymentFrequency Example: quarterly
		PaymentFrequency *string `json:"payment_frequency,omitempty"`
		Sector           *string `json:"sector,omitempty"`
		Symbol           string  `json:"symbol"`
	} `json:"stocks"`
}

// Dividend A dividend paid to you. All amounts are in the currency it was paid in.
type Dividend struct {
	// Amount Gross.
	Amount Money `json:"amount"`

	// Date Pay date.
	Date openapi_types.Date `json:"date"`
	Isin *string            `json:"isin,omitempty"`
	Name *string            `json:"name,omitempty"`

	// Net What reached you.
	Net            Money  `json:"net"`
	PerShareAmount *Money `json:"per_share_amount,omitempty"`

	// Portfolio Which portfolio, when you have more than one and didn't pick one.
	Portfolio *string `json:"portfolio,omitempty"`

	// Quantity Shares it was paid on.
	Quantity *int `json:"quantity,omitempty"`

	// Source How it was recorded, e.g. manual or an import.
	Source *string `json:"source,omitempty"`

	// Symbol Example: KO
	Symbol string `json:"symbol"`

	// WithholdingTax Withheld abroad.
	WithholdingTax *Money `json:"withholding_tax,omitempty"`
}

// DividendList defines model for DividendList.
type DividendList struct {
	Dividends []Dividend `json:"dividends"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Stable, for programs to branch on.
		Code ErrorErrorCode `json:"code"`

		// Message For humans; may change.
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode Stable, for programs to branch on.
type ErrorErrorCode string

// Holding defines model for Holding.
type Holding struct {
	// AverageCost Per share, in the currency the position trades in; full precision.
	AverageCost    Money   `json:"average_cost"`
	InstrumentType *string `json:"instrument_type,omitempty"`
	Isin           *string `json:"isin,omitempty"`
	Name           *string `json:"name"`

	// Portfolio Which portfolio, when you have more than one and didn't pick one.
	Portfolio *string `json:"portfolio,omitempty"`
	Sector    *string `json:"sector,omitempty"`

	// Shares A decimal string: shares can be fractional.
	Shares string `json:"shares"`

	// Symbol Example: KO
	Symbol string `json:"symbol"`
}

// HoldingList defines model for HoldingList.
type HoldingList struct {
	Holdings []Holding `json:"holdings"`
}

// Income Money is in your preferred currency throughout. Rates are fractions: 0.05 is 5%.
type Income struct {
	// AnnualIncome Forward, at today's rates, gross.
	AnnualIncome Money `json:"annual_income"`

	// CurrentYieldPct A percentage.
	CurrentYieldPct *float64 `json:"current_yield_pct,omitempty"`
	Drip            bool     `json:"drip"`

	// GrowthRate Income-weighted dividend growth, a fraction.
	GrowthRate *float64 `json:"growth_rate,omitempty"`

	// Holdings Where the income comes from, biggest first.
	Holdings []struct {
		// Cagr5y A fraction.
		Cagr5y *float64 `json:"cagr_5y,omitempty"`

		// Growth A fraction.
		Growth *float64 `json:"growth,omitempty"`

		// Income An amount and its currency. The amount is a decimal string, never a float.
		Income Money `json:"income"`

		// NetIncome An amount and its currency. The amount is a decimal string, never a float.
		NetIncome Money `json:"net_income"`

		// Streak Consecutive years of increases.
		Streak *int   `json:"streak,omitempty"`
		Symbol string `json:"symbol"`
	} `json:"holdings"`

	// IncomeYear How a typical year's income falls across the months. Null for a portfolio too small for the shape to mean anything.
	IncomeYear *struct {
		// AverageMonth An amount and its currency. The amount is a decimal string, never a float.
		AverageMonth  *Money `json:"average_month,omitempty"`
		BiggestMonths *[]int `json:"biggest_months,omitempty"`

		// BiggestMonthsShare Share of the year in the biggest months. 0.25 is perfectly even.
		BiggestMonthsShare *float64 `json:"biggest_months_share,omitempty"`

		// ByMonth Keyed by month, "1" to "12", every month present.
		ByMonth          *map[string]Money `json:"by_month,omitempty"`
		EmptyMonths      *[]int            `json:"empty_months,omitempty"`
		NetOfWithholding *bool             `json:"net_of_withholding,omitempty"`

		// ThinMonths Below average, thinnest first.
		ThinMonths *[]int `json:"thin_months,omitempty"`
	} `json:"income_year,omitempty"`

	// NetAnnualIncome The same, net of estimated foreign withholding.
	NetAnnualIncome Money `json:"net_annual_income"`

	// Projection One entry per year, from 0 (now) to `years`.
	Projection []struct {
		// Income An amount and its currency. The amount is a decimal string, never a float.
		Income Money `json:"income"`

		// NetIncome An amount and its currency. The amount is a decimal string, never a float.
		NetIncome  Money `json:"net_income"`
		YearOffset int   `json:"year_offset"`
	} `json:"projection"`
	Years int `json:"years"`
}

// Me The user the token belongs to.
type Me struct {
	Email string             `json:"email"`
	Id    openapi_types.UUID `json:"id"`
	Name  *string            `json:"name,omitempty"`

	// PreferredCurrency ISO 4217; the currency aggregates are reported in.
	//
	// Example: EUR
	PreferredCurrency string `json:"preferred_currency"`
}

// Money An amount and its currency. The amount is a decimal string, never a float.
type Money struct {
	// Amount Example: 12.34
	Amount string `json:"amount"`

	// Currency ISO 4217
	//
	// Example: EUR
	Currency string `json:"currency"`
}

// Portfolio Pass its name (or slug) as `portfolio` to narrow the ledger endpoints to it; without it they aggregate across all portfolios.
type Portfolio struct {
	Default bool   `json:"default"`
	Name    string `json:"name"`

	// Slug Present only when the portfolio is shared.
	Slug *string `json:"slug,omitempty"`
}

// PortfolioList defines model for PortfolioList.
type PortfolioList struct {
	Portfolios []Portfolio `json:"portfolios"`
}

// Stock defines model for Stock.
type Stock struct {
	// Currency The currency it trades in.
	Currency string `json:"currency"`
	Dividend struct {
		// Annual Per share, per year, from the live quote. Null without a token.
		Annual *Money `json:"annual,omitempty"`

		// Cagr5y A fraction.
		Cagr5y         *float64            `json:"cagr_5y,omitempty"`
		ExDividendDate *openapi_types.Date `json:"ex_dividend_date,omitempty"`

		// Frequency Example: quarterly
		Frequency     *string             `json:"frequency,omitempty"`
		PaymentMonths []int               `json:"payment_months"`
		Safety        StockDividendSafety `json:"safety"`

		// StreakYears Consecutive years of increases.
		StreakYears *int `json:"streak_years,omitempty"`

		// YieldAvg5yPct The average yield over about 5 years, a percentage.
		YieldAvg5yPct *float64 `json:"yield_avg_5y_pct,omitempty"`

		// YieldPct A percentage.
		YieldPct *float64 `json:"yield_pct,omitempty"`
	} `json:"dividend"`
	Industry *string `json:"industry,omitempty"`

	// InstrumentType Example: equity
	InstrumentType *string `json:"instrument_type,omitempty"`
	Name           *string `json:"name,omitempty"`

	// Price Money, plus whether it is live. Live with a token; without one, the last price Quantic stored and when. Null when there is neither.
	Price *struct {
		// Amount Example: 12.34
		Amount string `json:"amount"`

		// AsOf When the stored price was seen. Null for a live price.
		AsOf *time.Time `json:"as_of,omitempty"`

		// Currency ISO 4217
		//
		// Example: EUR
		Currency string `json:"currency"`
		Live     bool   `json:"live"`
	} `json:"price"`

	// Scores Quantic's 0–10 lenses.
	Scores struct {
		Momentum *float64 `json:"momentum,omitempty"`
		Rating   *float64 `json:"rating,omitempty"`
		Value    *float64 `json:"value,omitempty"`
	} `json:"scores"`
	Sector *string `json:"sector,omitempty"`

	// Symbol Example: KO
	Symbol string `json:"symbol"`
}

// StockDividendSafety defines model for Stock.Dividend.Safety.
type StockDividendSafety string

// StockSearch defines model for StockSearch.
type StockSearch struct {
	Results []struct {
		Exchange *string `json:"exchange,omitempty"`
		Name     *string `json:"name,omitempty"`
		Symbol   string  `json:"symbol"`

		// Tracked Quantic has data for it, so /api/v1/stocks/{symbol} answers.
		Tracked bool `json:"tracked"`

		// Type Example: EQUITY
		Type *string `json:"type,omitempty"`
	} `json:"results"`
}

// GetCalendarParams defines parameters for GetCalendar.
type GetCalendarParams struct {
	// Days How far ahead, 1 to 120. Default 45.
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListDividendsParams defines parameters for ListDividends.
type ListDividendsParams struct {
	// Symbol Only this ticker. An unknown one matches nothing.
	Symbol *string `form:"symbol,omitempty" json:"symbol,omitempty"`

	// From Paid on or after.
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Paid on or before.
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// Portfolio A portfolio name or slug, case-insensitive. Omitted: all portfolios, and each row says which one it is in when you have more than one.
	Portfolio *string `form:"portfolio,omitempty" json:"portfolio,omitempty"`
}

// ListHoldingsParams defines parameters for ListHoldings.
type ListHoldingsParams struct {
	// Portfolio A portfolio name or slug, case-insensitive. Omitted: all portfolios, and each row says which one it is in when you have more than one.
	Portfolio *string `form:"portfolio,omitempty" json:"portfolio,omitempty"`
}

// GetIncomeParams defines parameters for GetIncome.
type GetIncomeParams struct {
	// Years Projection horizon, 1 to 50. Default 10.
	Years *int `form:"years,omitempty" json:"years,omitempty"`

	// Drip Compound reinvested dividends. Default false.
	Drip *bool `form:"drip,omitempty" json:"drip,omitempty"`

	// Portfolio A portfolio name or slug, case-insensitive. Omitted: all portfolios.
	Portfolio *string `form:"portfolio,omitempty" json:"portfolio,omitempty"`
}

// SearchStocksParams defines parameters for SearchStocks.
type SearchStocksParams struct {
	// Q Ticker or name.
	Q string `form:"q" json:"q"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// genClient which conforms to the OpenAPI3 specification for this service.
type genClient struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*genClient) error

// Creates a new genClient, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*genClient, error) {
	// create a client with sane default values
	client := genClient{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *genClient) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *genClient) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCalendar Upcoming ex-dividend dates
	//
	// Every stock Quantic tracks going ex-dividend in the next `days` days, soonest first. Public: no token needed. Buy before the ex-date to receive the next dividend.
	//
	// Corresponds with GET /api/v1/calendar (the `GetCalendar` operationId).
	GetCalendar(ctx context.Context, params *GetCalendarParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDividends Your received dividends
	//
	// Dividends paid to you, newest first.
	//
	// Corresponds with GET /api/v1/dividends (the `ListDividends` operationId).
	ListDividends(ctx context.Context, params *ListDividendsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListHoldings Your holdings
	//
	// Each position's shares and average cost, from the ledger: cost basis, no live prices.
	//
	// Corresponds with GET /api/v1/holdings (the `ListHoldings` operationId).
	ListHoldings(ctx context.Context, params *ListHoldingsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIncome Your dividend income outlook
	//
	// Forward annual dividend income at today's rates, in your preferred currency, gross and net of estimated foreign withholding; the holdings it comes from; a year-by-year projection; and how a typical year's income falls across the months.
	//
	// Corresponds with GET /api/v1/income (the `GetIncome` operationId).
	GetIncome(ctx context.Context, params *GetIncomeParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMe The user the token belongs to
	//
	// Also the cheapest way to check that a token works.
	//
	// Corresponds with GET /api/v1/me (the `GetMe` operationId).
	GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPortfolios Your portfolios
	//
	// Corresponds with GET /api/v1/portfolios (the `ListPortfolios` operationId).
	ListPortfolios(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchStocks Search stocks
	//
	// By ticker or company name, up to about 10 matches. Anonymous callers search the stocks Quantic already tracks; with a token the search also asks the market-data provider.
	//
	// Corresponds with GET /api/v1/stocks (the `SearchStocks` operationId).
	SearchStocks(ctx context.Context, params *SearchStocksParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStock One stock
	//
	// Identity, price, dividend profile, dividend safety and the 0–10 scores. With a token the price is live; without one it is the last price Quantic stored, with its time.
	//
	// Corresponds with GET /api/v1/stocks/{symbol} (the `GetStock` operationId).
	GetStock(ctx context.Context, symbol string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCalendar Upcoming ex-dividend dates
//
// Every stock Quantic tracks going ex-dividend in the next `days` days, soonest first. Public: no token needed. Buy before the ex-date to receive the next dividend.
//
// Corresponds with GET /api/v1/calendar (the `GetCalendar` operationId).
func (c *genClient) GetCalendar(ctx context.Context, params *GetCalendarParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListDividends Your received dividends
//
// Dividends paid to you, newest first.
//
// Corresponds with GET /api/v1/dividends (the `ListDividends` operationId).
func (c *genClient) ListDividends(ctx context.Context, params *ListDividendsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDividendsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListHoldings Your holdings
//
// Each position's shares and average cost, from the ledger: cost basis, no live prices.
//
// Corresponds with GET /api/v1/holdings (the `ListHoldings` operationId).
func (c *genClient) ListHoldings(ctx context.Context, params *ListHoldingsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListHoldingsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetIncome Your dividend income outlook
//
// Forward annual dividend income at today's rates, in your preferred currency, gross and net of estimated foreign withholding; the holdings it comes from; a year-by-year projection; and how a typical year's income falls across the months.
//
// Corresponds with GET /api/v1/income (the `GetIncome` operationId).
func (c *genClient) GetIncome(ctx context.Context, params *GetIncomeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIncomeRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMe The user the token belongs to
//
// Also the cheapest way to check that a token works.
//
// Corresponds with GET /api/v1/me (the `GetMe` operationId).
func (c *genClient) GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListPortfolios Your portfolios
//
// Corresponds with GET /api/v1/portfolios (the `ListPortfolios` operationId).
func (c *genClient) ListPortfolios(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPortfoliosRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SearchStocks Search stocks
//
// By ticker or company name, up to about 10 matches. Anonymous callers search the stocks Quantic already tracks; with a token the search also asks the market-data provider.
//
// Corresponds with GET /api/v1/stocks (the `SearchStocks` operationId).
func (c *genClient) SearchStocks(ctx context.Context, params *SearchStocksParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchStocksRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetStock One stock
//
// Identity, price, dividend profile, dividend safety and the 0–10 scores. With a token the price is live; without one it is the last price Quantic stored, with its time.
//
// Corresponds with GET /api/v1/stocks/{symbol} (the `GetStock` operationId).
func (c *genClient) GetStock(ctx context.Context, symbol string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStockRequest(c.Server, symbol)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCalendarRequest constructs an http.Request for the GetCalendar method
func NewGetCalendarRequest(server string, params *GetCalendarParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendar")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Days != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "days", *params.Days, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDividendsRequest constructs an http.Request for the ListDividends method
func NewListDividendsRequest(server string, params *ListDividendsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/dividends")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Symbol != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "symbol", *params.Symbol, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "from", *params.From, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "to", *params.To, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Portfolio != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "portfolio", *params.Portfolio, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListHoldingsRequest constructs an http.Request for the ListHoldings method
func NewListHoldingsRequest(server string, params *ListHoldingsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/holdings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Portfolio != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "portfolio", *params.Portfolio, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIncomeRequest constructs an http.Request for the GetIncome method
func NewGetIncomeRequest(server string, params *GetIncomeParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/income")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Years != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "years", *params.Years, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Drip != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "drip", *params.Drip, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Portfolio != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "portfolio", *params.Portfolio, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMeRequest constructs an http.Request for the GetMe method
func NewGetMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListPortfoliosRequest constructs an http.Request for the ListPortfolios method
func NewListPortfoliosRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/portfolios")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchStocksRequest constructs an http.Request for the SearchStocks method
func NewSearchStocksRequest(server string, params *SearchStocksParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/stocks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStockRequest constructs an http.Request for the GetStock method
func NewGetStockRequest(server string, symbol string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "symbol", symbol, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/stocks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *genClient) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *genClient) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetCalendarWithResponse Upcoming ex-dividend dates
	//
	// Every stock Quantic tracks going ex-dividend in the next `days` days, soonest first. Public: no token needed. Buy before the ex-date to receive the next dividend.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/calendar (the `GetCalendar` operationId).
	GetCalendarWithResponse(ctx context.Context, params *GetCalendarParams, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error)

	// ListDividendsWithResponse Your received dividends
	//
	// Dividends paid to you, newest first.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/dividends (the `ListDividends` operationId).
	ListDividendsWithResponse(ctx context.Context, params *ListDividendsParams, reqEditors ...RequestEditorFn) (*ListDividendsResponse, error)

	// ListHoldingsWithResponse Your holdings
	//
	// Each position's shares and average cost, from the ledger: cost basis, no live prices.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/holdings (the `ListHoldings` operationId).
	ListHoldingsWithResponse(ctx context.Context, params *ListHoldingsParams, reqEditors ...RequestEditorFn) (*ListHoldingsResponse, error)

	// GetIncomeWithResponse Your dividend income outlook
	//
	// Forward annual dividend income at today's rates, in your preferred currency, gross and net of estimated foreign withholding; the holdings it comes from; a year-by-year projection; and how a typical year's income falls across the months.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/income (the `GetIncome` operationId).
	GetIncomeWithResponse(ctx context.Context, params *GetIncomeParams, reqEditors ...RequestEditorFn) (*GetIncomeResponse, error)

	// GetMeWithResponse The user the token belongs to
	//
	// Also the cheapest way to check that a token works.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/me (the `GetMe` operationId).
	GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResponse, error)

	// ListPortfoliosWithResponse Your portfolios
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/portfolios (the `ListPortfolios` operationId).
	ListPortfoliosWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPortfoliosResponse, error)

	// SearchStocksWithResponse Search stocks
	//
	// By ticker or company name, up to about 10 matches. Anonymous callers search the stocks Quantic already tracks; with a token the search also asks the market-data provider.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/stocks (the `SearchStocks` operationId).
	SearchStocksWithResponse(ctx context.Context, params *SearchStocksParams, reqEditors ...RequestEditorFn) (*SearchStocksResponse, error)

	// GetStockWithResponse One stock
	//
	// Identity, price, dividend profile, dividend safety and the 0–10 scores. With a token the price is live; without one it is the last price Quantic stored, with its time.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/stocks/{symbol} (the `GetStock` operationId).
	GetStockWithResponse(ctx context.Context, symbol string, reqEditors ...RequestEditorFn) (*GetStockResponse, error)
}

type GetCalendarResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Calendar
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCalendarResponse) GetJSON200() *Calendar {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r GetCalendarResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r GetCalendarResponse) GetJSON429() *Error {
	return r.JSON429
}

// GetBody returns the raw response body bytes
func (r GetCalendarResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCalendarResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCalendarResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDividendsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DividendList
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDividendsResponse) GetJSON200() *DividendList {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListDividendsResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r ListDividendsResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r ListDividendsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDividendsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDividendsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDividendsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListHoldingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *HoldingList
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListHoldingsResponse) GetJSON200() *HoldingList {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListHoldingsResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r ListHoldingsResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r ListHoldingsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListHoldingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListHoldingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListHoldingsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetIncomeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Income
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetIncomeResponse) GetJSON200() *Income {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetIncomeResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r GetIncomeResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r GetIncomeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetIncomeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIncomeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetIncomeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Me
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetMeResponse) GetJSON200() *Me {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetMeResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r GetMeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListPortfoliosResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PortfolioList
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListPortfoliosResponse) GetJSON200() *PortfolioList {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListPortfoliosResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r ListPortfoliosResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListPortfoliosResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPortfoliosResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPortfoliosResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SearchStocksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *StockSearch
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SearchStocksResponse) GetJSON200() *StockSearch {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r SearchStocksResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r SearchStocksResponse) GetJSON429() *Error {
	return r.JSON429
}

// GetBody returns the raw response body bytes
func (r SearchStocksResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SearchStocksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchStocksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchStocksResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetStockResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Stock
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetStockResponse) GetJSON200() *Stock {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetStockResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r GetStockResponse) GetJSON429() *Error {
	return r.JSON429
}

// GetBody returns the raw response body bytes
func (r GetStockResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetStockResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStockResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetStockResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCalendarWithResponse Upcoming ex-dividend dates
//
// Every stock Quantic tracks going ex-dividend in the next `days` days, soonest first. Public: no token needed. Buy before the ex-date to receive the next dividend.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/calendar (the `GetCalendar` operationId).
func (c *ClientWithResponses) GetCalendarWithResponse(ctx context.Context, params *GetCalendarParams, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error) {
	rsp, err := c.GetCalendar(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarResponse(rsp)
}

// ListDividendsWithResponse Your received dividends
//
// Dividends paid to you, newest first.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/dividends (the `ListDividends` operationId).
func (c *ClientWithResponses) ListDividendsWithResponse(ctx context.Context, params *ListDividendsParams, reqEditors ...RequestEditorFn) (*ListDividendsResponse, error) {
	rsp, err := c.ListDividends(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDividendsResponse(rsp)
}

// ListHoldingsWithResponse Your holdings
//
// Each position's shares and average cost, from the ledger: cost basis, no live prices.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/holdings (the `ListHoldings` operationId).
func (c *ClientWithResponses) ListHoldingsWithResponse(ctx context.Context, params *ListHoldingsParams, reqEditors ...RequestEditorFn) (*ListHoldingsResponse, error) {
	rsp, err := c.ListHoldings(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListHoldingsResponse(rsp)
}

// GetIncomeWithResponse Your dividend income outlook
//
// Forward annual dividend income at today's rates, in your preferred currency, gross and net of estimated foreign withholding; the holdings it comes from; a year-by-year projection; and how a typical year's income falls across the months.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/income (the `GetIncome` operationId).
func (c *ClientWithResponses) GetIncomeWithResponse(ctx context.Context, params *GetIncomeParams, reqEditors ...RequestEditorFn) (*GetIncomeResponse, error) {
	rsp, err := c.GetIncome(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIncomeResponse(rsp)
}

// GetMeWithResponse The user the token belongs to
//
// Also the cheapest way to check that a token works.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/me (the `GetMe` operationId).
func (c *ClientWithResponses) GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResponse, error) {
	rsp, err := c.GetMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMeResponse(rsp)
}

// ListPortfoliosWithResponse Your portfolios
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/portfolios (the `ListPortfolios` operationId).
func (c *ClientWithResponses) ListPortfoliosWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPortfoliosResponse, error) {
	rsp, err := c.ListPortfolios(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPortfoliosResponse(rsp)
}

// SearchStocksWithResponse Search stocks
//
// By ticker or company name, up to about 10 matches. Anonymous callers search the stocks Quantic already tracks; with a token the search also asks the market-data provider.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/stocks (the `SearchStocks` operationId).
func (c *ClientWithResponses) SearchStocksWithResponse(ctx context.Context, params *SearchStocksParams, reqEditors ...RequestEditorFn) (*SearchStocksResponse, error) {
	rsp, err := c.SearchStocks(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchStocksResponse(rsp)
}

// GetStockWithResponse One stock
//
// Identity, price, dividend profile, dividend safety and the 0–10 scores. With a token the price is live; without one it is the last price Quantic stored, with its time.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/stocks/{symbol} (the `GetStock` operationId).
func (c *ClientWithResponses) GetStockWithResponse(ctx context.Context, symbol string, reqEditors ...RequestEditorFn) (*GetStockResponse, error) {
	rsp, err := c.GetStock(ctx, symbol, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStockResponse(rsp)
}

// ParseGetCalendarResponse parses an HTTP response from a GetCalendarWithResponse call
func ParseGetCalendarResponse(rsp *http.Response) (*GetCalendarResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Calendar
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseListDividendsResponse parses an HTTP response from a ListDividendsWithResponse call
func ParseListDividendsResponse(rsp *http.Response) (*ListDividendsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDividendsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DividendList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListHoldingsResponse parses an HTTP response from a ListHoldingsWithResponse call
func ParseListHoldingsResponse(rsp *http.Response) (*ListHoldingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListHoldingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HoldingList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetIncomeResponse parses an HTTP response from a GetIncomeWithResponse call
func ParseGetIncomeResponse(rsp *http.Response) (*GetIncomeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIncomeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Income
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetMeResponse parses an HTTP response from a GetMeWithResponse call
func ParseGetMeResponse(rsp *http.Response) (*GetMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Me
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseListPortfoliosResponse parses an HTTP response from a ListPortfoliosWithResponse call
func ParseListPortfoliosResponse(rsp *http.Response) (*ListPortfoliosResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPortfoliosResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PortfolioList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseSearchStocksResponse parses an HTTP response from a SearchStocksWithResponse call
func ParseSearchStocksResponse(rsp *http.Response) (*SearchStocksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchStocksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StockSearch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseGetStockResponse parses an HTTP response from a GetStockWithResponse call
func ParseGetStockResponse(rsp *http.Response) (*GetStockResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStockResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Stock
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}
